@startuml

title __MODEL's Class Diagram__\n

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      class hk.edu.polyu.comp.comp3211.monopoly.model.Board {
          - p_index : int
          - players : Player[]
          - round : int
          - squares : ISquare[]
          + Board()
          + getP_index()
          + getPlayers()
          + getRound()
          + getSquares()
          + load()
          + save()
          + setP_index()
          + setRound()
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      class hk.edu.polyu.comp.comp3211.monopoly.model.Player {
          - bankrupted : boolean
          - inJail : int
          - money : int
          - name : String
          - position : int
          - properties : Property[]
          + Player()
          + bankrupt()
          + getInJail()
          + getMoney()
          + getName()
          + getPosition()
          + goToJail()
          + isBankrupted()
          + move()
          + rollDice()
          + setInJail()
          + setMoney()
          + setName()
          + setPosition()
      }
    }
  }
  



right footer


COMP3211 Software Engineering Course Project: Monopoly, 2021 Fall
by Group 22: MAN Furui, LIU Sicheng, WANG Meng, XING Shiji
endfooter

@enduml
