@startuml

title __SQUARES's Class Diagram__\n

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Chance {
            + execute()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Free {
            + execute()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Go {
            + execute()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        interface hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare {
            {abstract} + execute()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Jail {
            + execute()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Oops {
            + execute()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Property {
            - name : String
            - price : int
            - rent : int
            + Property()
            + execute()
            + getName()
            + getOwner()
            + setOwner()
        }
      }
    }
  }
  

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace model {
      namespace squares {
        class hk.edu.polyu.comp.comp3211.monopoly.model.squares.Tax {
            + execute()
        }
      }
    }
  }
  

  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Chance .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Free .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Go .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Jail .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Oops .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Property .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Property o-- hk.edu.polyu.comp.comp3211.monopoly.model.Player : owner
  hk.edu.polyu.comp.comp3211.monopoly.model.squares.Tax .up.|> hk.edu.polyu.comp.comp3211.monopoly.model.squares.ISquare


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
