@startuml

title __VIEW's Class Diagram__\n

  namespace hk.edu.polyu.comp.comp3211.monopoly {
    namespace view {
      class hk.edu.polyu.comp.comp3211.monopoly.view.Printer {
          + Print()
          + Printer()
      }
    }
  }
  

  hk.edu.polyu.comp.comp3211.monopoly.view.Printer o-- hk.edu.polyu.comp.comp3211.monopoly.model.Board : board


right footer


COMP3211 Software Engineering Course Project: Monopoly, 2021 Fall
by Group 22: MAN Furui, LIU Sicheng, WANG Meng, XING Shiji
endfooter

@enduml
